baseurl: /
languageCode: en-AU
title: qMalaria
theme: hugo-lithium
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  news: /news/:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Our Team
      url: /our-team/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: News
      url: /news/
      weight: 4
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
